### ISSUE TITLE
Remove themes notice

### ISSUE THREAD

**Issue by sujaypawar** [Nikschavan/header-footer-elementor#101]
Remove themes notice: 
http://screenshots.sharkz.in/sujay/180417124735.png

**Comment by Nikschavan** [comment]
I think we should first implement #107 first and then remove the notice.
Else there will be angry users with 1-Star ratings - https://wordpress.org/support/topic/compatible-yet-not/

**Comment by jpSimkins** [comment]
This nag is too invasive. To not have an option to ignore is simply bad programming. We cannot get rid of this nag even tho we followed this guide: https://github.com/Nikschavan/header-footer-elementor/wiki/Adding-Header-Footer-Elementor-support-for-your-theme

We have since decided to drop this plugin because of this nag. Clients do NOT want to see this.

**Comment by Nikschavan** [comment]
@jpSimkins 

Declaring the theme support from your theme/child theme should hide the nag. Did you try this snippet?

 ```function your_prefix_header_footer_elementor_support() {
	add_theme_support( 'header-footer-elementor' );
}

add_action( 'after_setup_theme', 'your_prefix_header_footer_elementor_support' );```

**Comment by jpSimkins** [comment]
@Nikschavan Yes, I have tried that and I still have the nag.Perhaps an update has prevented that from removing the nag? I haven't had time to look too much into this yet but following [this](https://github.com/Nikschavan/header-footer-elementor/wiki/Adding-Header-Footer-Elementor-support-for-your-theme) page and even using your snipped above did not remove the nag.
