### ISSUE TITLE
pojo themes

### ISSUE THREAD

**Issue by antoine0579** [Nikschavan/header-footer-elementor#15]
when will header footer elementor plugin be compatible with pojo themes, the creator of elementor?

**Comment by Nikschavan** [comment]
As those are the premium themes, I will try to contact the developers If I can get access to their themes for adding support with the plugin. 

I will contact then at the time of adding new theme support for the next update (#11)

**Comment by Nikschavan** [comment]
Hello @antoine0579,

I have recently [updated the wiki](https://github.com/Nikschavan/header-footer-elementor/wiki/Adding-Header-Footer-Elementor-support-for-your-theme) to allow theme authors to add support for the plugin, It's just a few lines of code.

Since themes by pojo are premium I will have to purchase them in order to add support, Although you can give them a link to this tutorial and they can add support for the plugin from the theme.
