### ISSUE TITLE
Footer is not shown

### ISSUE THREAD

**Issue by Noahtro** [Nikschavan/header-footer-elementor#264]
Hi, 

i´m new here to Github :D So, I´ve edited the footer and set them to all pages on the website and to show to all. But somehow it is not shown on the website. In the support I´ve also activated these two methods but there is still nothing changing. I hope you can help me :)

Kind regards
Noah

**Comment by vrundakansara** [comment]
Hey @Noahtro ,

Thank you for reaching us out. That does not happen ideally. Is the footer that you built published?
Is there any other Footer active too?

If none of the options work for you, you can reach us out [here](http://uaelementor.com/support/), so that we debug the issue closely.

Regards,
Vrunda Kansara

**Comment by SuryawanshiPrajakta** [comment]
Hello @Noahtro,

I could see that you had opened a ticket and our support team member has helped you in resolving this issue.

Elementor - Header, Footer and Blocks will work only with Elementor page builder. It will not show you expected results if you use this with any other page builder.

I hope this helps. Do let us know if we can help with something else.

Regards,
Prajakta Suryawanshi
