### ISSUE TITLE
Footer isn't loaded translated in multi language pages

### ISSUE THREAD

**Issue by Madquake** [Nikschavan/header-footer-elementor#280]
Hello,
I have a problem with a website I'm working on, https://www.cinqueteste.com

I added a multilanguage footer. The addon allows me to create a translated version of the footer for each language but when I load the translated page (in my case "English") the footer loaded is still the Italian one.

For this site I used the standard TwentySeventeen Theme.

Have you ever encountered a similar problem before?

Thank you so much for your help!

**Comment by SuryawanshiPrajakta** [comment]
Hello @Madquake,

Thank you for getting in touch!

Elementor - Header, Footer and Blocks as of now is not compatible with Polylang plugin. If you are using Polylang to translate the footer, then I am glad to let you know that this issue will be fixed soon.

But, if you are trying to achieve this through WPML, then we will recommend you to open a support ticket from [here](https://www.brainstormforce.com/open-a-ticket/) so that we can check this issue closely.

Looking forward to hearing from you.

Regards,
Prajakta Suryawanshi

**Comment by SuryawanshiPrajakta** [comment]
Hey @Madquake,

I am glad to let you know that EHF v1.5.2 is released and with this, we have added compatibility to Polylang!

Please upgrade EHF to the latest version. The multi-language footer should work fine now.

Regards,
Prajakta Suryawanshi
