### ISSUE TITLE
how to add elementor footer to my astra theme

### ISSUE THREAD

**Issue by vikrampalakurti** [Nikschavan/header-footer-elementor#327]
Please help me

**Comment by pratikshasaman** [comment]
Hello @vikrampalakurti,

Apologies for the delay in response!

Elementor - Header, Footer, and Blocks Template plugin, helps you to build a header, footer, and a custom block for your site.

In order to create a footer, please follow the below steps -

- Visit your website dashboard

- Appearance > Header, Footer, and Blocks > Add new > and select the template you want.

'Display on' setting will help you to add a condition where the template should appear. EHF also provides a default widget, please have a look - https://a.cl.ly/QwuknJ0n

I hope the information will help. Let us know if you have further queries.

**Comment by SuryawanshiPrajakta** [comment]
Hello @vikrampalakurti,

We are closing this query as we did not hear back from you. I hope the steps provided helped you.

Please do not hesitate to get back to us if you still face any hurdle.

Regards,
Prajakta Suryawanshi
