### ISSUE TITLE
Sticky Header/menu support for Astra

### ISSUE THREAD

**Issue by thinxx** [Nikschavan/header-footer-elementor#57]
Any idea on how to enable sticky header support for the Astra Theme. I'm quite far along with my site and don't want to have to change themes again because of this on issue. It's a vital function for me though.

I am using the latest Astra Theme(Child), Elementor, Header/Footer 1.0.7 with Wordpress 4.9.
I hope you can help cos I'm getting quite confused now. Thanks!

**Comment by Nikschavan** [comment]
Transparent Header functionality will probably come with future updates to the plugin. Right now it is not possible.

Since you are using Astra, The [Pro package of Astra](https://wpastra.com/pricing/) comes with this feature so you can create sticky headers with much more options like targeting the header on a specific page, category etc. Also Astra Pro extends the theme with much more other options.

**Comment by thinxx** [comment]
Thanks Nikschavan. 
After a lot of trial & error I did manage to achieve the desired effect. 

Appreciate your help though, have a great day further.
